export const childDropdownData = [
  {
    text: "Icon",
    value: "Icon",
    details: {
      icon: "",
      color: "",
      size: "",
    },
  },
  {
    text: "Flatbutton",
    value: "Flatbutton",
    details: {
      color: "",
      splashColor: "",
      textColor: "",
      text: "",
      disabledTextColor: "",
      disabledColor: "",
      shape: "",
      onPressed: "",
      padding: "",
      highlightColor: "",
    },
  },
  {
    text: "TextField",
    value: "TextField",
    details: {
      cursorColor: "",
      cursorWidth: "",
      maxLength: "",
      maxLines: "",
      decoration: "",
      style: "",
      textDirection: "",
      textAlign: "",
    },
  },
  {
    text: "CheckBox",
    value: "CheckBox",
    details: {
      activeColor: "",
      checkColor: "",
      parameter: "",
    },
  },
  {
    text: "RadioListTile",
    value: "RadioListTile",
    details: {
      activeColor: "",
      title: "",
      subtitle: "",
      parameter: "",
    },
  },
  {
    text: "Switch",
    value: "Switch",
    details: {
      activeColor: "",
      focusColor: "",
      activeTrackColor: "",
      hoverColor: "",
      parameter: "",
    },
  },
  {
    text: "Text",
    value: "Text",
    details: {
      textValue: "",
      style: "",
      textAlign: "",
      textDirection: "",
      maxLines: "",
      textScaleFactor: "",
    },
  },
  {
    text: "IconButton",
    value: "IconButton",
    details: {
      icon: "",
      iconSize: "",
      color: "",
      splashColor: "",
      tooltip: "",
      highlightColor: "",
      disabledColor: "",
      focusColor: "",
      padding: "",
      visualDensity: "",
      onPressed: "",
    },
  },
  {
    text: "RaisedButton",
    value: "RaisedButton",
    details: {
      color: "",
      splashColor: "",
      shape: "",
      text: "",
      padding: "",
      textColor: "",
      highlightColor: "",
      disabledColor: "",
      disabledTextColor: "",
      focusColor: "",
      elevation: "",
      //textTheme: "",
      onPressed: "",
    },
  },
  {
    text: "OutlineButton",
    value: "OutlineButton",
    details: {
      color: "",
      splashColor: "",
      shape: "",
      text: "",
      padding: "",
      textColor: "",
      highlightedBorderColor: "",
      disabledBorderColor: "",
      disabledTextColor: "",
      focusColor: "",
      highlightElevation: "",
      borderSide: "",
      // textTheme: "",
      onPressed: "",
    },
  },
  {
    text: "DatePicker",
    value: "DatePicker",
    details: {
      errorFormatText: "",
      errorInvalidText: "",
      firstDate: "",
      lastDate: "",
    },
  },
  {
    text: "TimePicker",
    value: "TimePicker",
    details: {
      helpText: "",
      cancelText: "",
      confirmText: "",
    },
  },
  {
    text: "Slider",
    value: "Slider",
    details: {
      activeColor: "",
      inactiveColor: "",
      min: "",
      max: "",
      divisions: "",
      label: "",
      parameterName: "",
      parameterValue: "",
    },
  },
  {
    text: "Divider",
    value: "Divider",
    details: {
      color: "",
      dividerHeight: "",
      thickness: "",
      indent: "",
      endIndent: "",
    },
  },
  {
    text: "LinearProgressIndicator",
    value: "LinearProgressIndicator",
    details: {
      backgroundColor: "",
      valueColor: "",
      minHeight: "",
    },
  },
  {
    text: "CircularProgressIndicator",
    value: "CircularProgressIndicator",
    details: {
      backgroundColor: "",
      strokeWidth: "",
    },
  },
  {
    text: "SizedBox",
    value: "SizedBox",
    details: {
      boxHeight: "",
      boxWidth: "",
    },
  },
  {
    text: "FloatingActionButton",
    value: "FloatingActionButton",
    details: {
      //color: "",
      floatingIcon: "",
      splashColor: "",
      shape: "",
      highlightElevation: "",
      //padding: "",
      foregroundColor: "",
      backgroundColor: "",
      //disabledColor: "",
      focusColor: "",
      elevation: "",
      mini: "",
      onPressed: "",
    },
  },
  {
    text: "Listtile",
    value: "Listtile",
    details: {
      title: "",
      subtitle: "",
      trailing: "",
      leading: "",
      enabled: "",
      selected: "",
      dense: "",
      onTap: "",
    },
  },

  {
    text: "ToolTip",
    value: "ToolTip",
    details: {
      message: "",
      margin: "",

      padding: "",
      showDuration: "",
      toolHeight: "",
      waitDuration: "",
      iconButton: "",
      onPressed: "",
    },
  },
  {
    text: "RangeSlider",
    value: "RangeSlider",
    details: {
      activeColor: "",
      inactiveColor: "",
      min: "",
      max: "",
      divisions: "",
      startParameter: "",
      startValue: "",
      endParameter: "",
      endValue: "",
    },
  },
  {
    text: "VerticalDivider",
    value: "VerticalDivider",
    details: {
      color: "",
      thickness: "",
      endIndent: "",
    },
  },
  {
    text: "Image",
    value: "Image",
    details: {
      url: "",
      imageHeight: "",
      imageWidth: "",
      fit: "",
      color: "",
      cacheHeight: "",
      cacheWidth: "",
      centerSlice: "",
      Alignment: "",
      repeat: "",
      colorBlendMode: "",
      gaplessPlayback: "",
      isAntiAlias: "",
      matchTextDirection: "",
      onTap: "",
    },
  },
];

export const parentDropdownData = [
  {
    text: "Icon",
    value: "Icon",
    details: {
      top: "",
      left: "",
      height: "",
      width: "",
      icon: "",
      color: "",
      size: "",
    },
  },
  {
    text: "TextField",
    value: "TextField",
    details: {
      top: "",
      left: "",
      height: "",
      width: "",
      cursorColor: "",
      cursorWidth: "",
      maxLength: "",
      maxLines: "",
      decoration: "",
      style: "",
      textDirection: "",
      textAlign: "",
    },
  },
  {
    text: "RadioListTile",
    value: "RadioListTile",
    details: {
      top: "",
      left: "",
      height: "",
      width: "",
      activeColor: "",
      title: "",
      subtitle: "",
      parameter: "",
    },
  },
  {
    text: "Flatbutton",
    value: "Flatbutton",
    details: {
      top: "",
      left: "",
      height: "",
      width: "",
      color: "",
      splashColor: "",
      textColor: "",
      shape: "",
      text: "",
      disabledTextColor: "",
      disabledColor: "",
      // textTheme: "",
      onPressed: "",
      padding: "",
      highlightColor: "",
    },
  },
  {
    text: "CheckBox",
    value: "CheckBox",
    details: {
      top: "",
      left: "",
      height: "",
      width: "",
      activeColor: "",
      checkColor: "",
      parameter: "",
    },
  },

  {
    text: "Switch",
    value: "Switch",
    details: {
      top: "",
      left: "",
      height: "",
      width: "",
      activeColor: "",
      focusColor: "",
      activeTrackColor: "",
      hoverColor: "",
      parameter: "",
    },
  },
  {
    text: "Text",
    value: "Text",
    details: {
      top: "",
      left: "",
      height: "",
      width: "",
      textValue: "",
      style: "",
      textAlign: "",
      textDirection: "",
      maxLines: "",
      textScaleFactor: "",
    },
  },
  {
    text: "IconButton",
    value: "IconButton",
    details: {
      top: "",
      left: "",
      height: "",
      width: "",
      iconSize: "",
      icon: "",
      color: "",
      splashColor: "",
      tooltip: "",
      highlightColor: "",
      disabledColor: "",
      focusColor: "",
      padding: "",
      visualDensity: "",
      onPressed: "",
    },
  },
  {
    text: "RaisedButton",
    value: "RaisedButton",
    details: {
      top: "",
      left: "",
      height: "",
      width: "",
      color: "",
      splashColor: "",
      shape: "",
      text: "",
      padding: "",
      textColor: "",
      highlightColor: "",
      disabledColor: "",
      disabledTextColor: "",
      focusColor: "",
      elevation: "",
      // textTheme: "",
      onPressed: "",
    },
  },
  {
    text: "OutlineButton",
    value: "OutlineButton",
    details: {
      top: "",
      left: "",
      height: "",
      width: "",
      color: "",
      splashColor: "",
      shape: "",
      text: "",
      padding: "",
      textColor: "",
      highlightedBorderColor: "",
      disabledBorderColor: "",
      disabledTextColor: "",
      focusColor: "",
      highlightElevation: "",
      borderSide: "",
      // textTheme: "",
      onPressed: "",
    },
  },
  {
    text: "Slider",
    value: "Slider",
    details: {
      top: "",
      left: "",
      height: "",
      width: "",
      activeColor: "",
      inactiveColor: "",
      min: "",
      max: "",
      divisions: "",
      label: "",
      parameterName: "",
      parameterValue: "",
    },
  },
  {
    text: "Divider",
    value: "Divider",
    details: {
      top: "",
      left: "",
      height: "",
      width: "",
      color: "",
      thickness: "",
      indent: "",
      endIndent: "",
      dividerHeight: "",
    },
  },
  {
    text: "LinearProgressIndicator",
    value: "LinearProgressIndicator",
    details: {
      top: "",
      left: "",
      height: "",
      width: "",
      backgroundColor: "",
      valueColor: "",
      minHeight: "",
    },
  },
  {
    text: "CircularProgressIndicator",
    value: "CircularProgressIndicator",
    details: {
      top: "",
      left: "",
      height: "",
      width: "",
      backgroundColor: "",
      strokeWidth: "",
    },
  },

  {
    text: "FloatingActionButton",
    value: "FloatingActionButton",
    details: {
      top: "",
      left: "",
      height: "",
      width: "",
      floatingIcon: "",
      splashColor: "",
      shape: "",
      highlightElevation: "",
      //padding: "",
      foregroundColor: "",
      backgroundColor: "",
      //disabledColor: "",
      focusColor: "",
      elevation: "",
      mini: "",
      onPressed: "",
    },
  },
  {
    text: "Listtile",
    value: "Listtile",
    details: {
      top: "",
      left: "",
      height: "",
      width: "",
      title: "",
      subtitle: "",
      trailing: "",
      leading: "",
      enabled: "",
      selected: "",
      dense: "",
      onTap: "",
    },
  },
  {
    text: "DatePicker",
    value: "DatePicker",
    details: {
      top: "",
      left: "",
      height: "",
      width: "",

      errorFormatText: "",
      errorInvalidText: "",
      firstDate: "",
      lastDate: "",
    },
  },
  {
    text: "TimePicker",
    value: "TimePicker",
    details: {
      top: "",
      left: "",
      height: "",
      width: "",
      helpText: "",
      cancelText: "",
      confirmText: "",
    },
  },
  {
    text: "SelectableText",
    value: "SelectableText",
    details: {
      textValue: "",
      top: "",
      left: "",
      height: "",
      width: "",
      style: "",
      textAlign: "",
      textDirection: "",
      maxLines: "",
      textScaleFactor: "",
    },
  },
  {
    text: "ToolTip",
    value: "ToolTip",
    details: {
      top: "",
      left: "",
      height: "",
      width: "",
      message: "",
      margin: "",
      padding: "",
      showDuration: "",
      toolHeight: "",
      waitDuration: "",
      iconButton: "",
      onPressed: "",
    },
  },
  {
    text: "RangeSlider",
    value: "RangeSlider",
    details: {
      top: "",
      left: "",
      height: "",
      width: "",
      activeColor: "",
      inactiveColor: "",
      min: "",
      max: "",
      divisions: "",
      startParameter: "",
      startValue: "",
      endParameter: "",
      endValue: "",
    },
  },
  {
    text: "VerticalDivider",
    value: "VerticalDivider",
    details: {
      top: "",
      left: "",
      height: "",
      width: "",
      color: "",
      thickness: "",
      endIndent: "",
    },
  },
  {
    text: "Card",
    value: "Card",
    details: {
      top: "",
      left: "",
      height: "",
      width: "",
      shadowColor: "",
      margin: "",
      shape: "",
      color: "",
      elevation: "",
      onTap: "",
      child: [],
    },
  },
  {
    text: "SizedBox",
    value: "SizedBox",
    details: {
      top: "",
      left: "",
      height: "",
      width: "",
      boxHeight: "",
      boxWidth: "",
    },
  },
  {
    text: "ToggleButtons",
    value: "ToggleButtons",
    details: {
      top: "",
      left: "",
      height: "",
      width: "",
      highlightColor: "",
      color: "",
      disabledColor: "",
      hoverColor: "",
      focusColor: "",
      borderColor: "",
      borderRadius: "",
      borderWidth: "",
      disabledBorderColor: "",
      fillColor: "",
      renderBorder: "",
      selectedBorderColor: "",
      selectedColor: "",
      textStyle: "",
      child: [],
    },
  },
  {
    text: "SimpleDialog",
    value: "SimpleDialog",
    details: {
      top: "",
      left: "",
      height: "",
      width: "",
      backgroundColor: "",
      contentPadding: "",
      titlePadding: "",
      shape: "",
      elevation: "",
      title: "",
      titleTextStyle: "",
      child: [
        {
          text: "SimpleDialogOption",
          value: "SimpleDialogOption",
          details: {
            text: "",
            padding: "",
            onPressedValue: "",
          },
        },
      ],
    },
  },
  {
    text: "ButtonBar",
    value: "ButtonBar",
    details: {
      top: "",
      left: "",
      height: "",
      width: "",
      alignment: "",
      buttonAlignedDropdown: "",
      buttonHeight: "",
      buttonMinWidth: "",
      buttonTextTheme: "",
      layoutBehavior: "",
      mainAxisSize: "",
      overflowButtonSpacing: "",
      overflowDirection: "",
      child: [
        {
          text: "Flatbutton",
          value: "Flatbutton",
          details: {
            color: "",
            splashColor: "",
            textColor: "",
            text: "",
            disabledTextColor: "",
            disabledColor: "",
            shape: "",
            //textTheme: "",
            onPressed: "",
            padding: "",
            highlightColor: "",
          },
        },
        {
          text: "IconButton",
          value: "IconButton",
          details: {
            icon: "",
            iconSize: "",
            color: "",
            splashColor: "",
            tooltip: "",
            highlightColor: "",
            disabledColor: "",
            focusColor: "",
            padding: "",
            visualDensity: "",
            onPressed: "",
          },
        },
        {
          text: "FloatingActionButton",
          value: "FloatingActionButton",
          details: {
            //color: "",
            floatingIcon: "",
            splashColor: "",
            shape: "",
            highlightElevation: "",
            //padding: "",
            foregroundColor: "",
            backgroundColor: "",
            //disabledColor: "",
            focusColor: "",
            elevation: "",
            mini: "",
            onPressed: "",
          },
        },

        {
          text: "RaisedButton",
          value: "RaisedButton",
          details: {
            color: "",
            splashColor: "",
            shape: "",
            text: "",
            padding: "",
            textColor: "",
            highlightColor: "",
            disabledColor: "",
            disabledTextColor: "",
            focusColor: "",
            elevation: "",
            // textTheme: "",
            onPressed: "",
          },
        },
        {
          text: "OutlineButton",
          value: "OutlineButton",
          details: {
            color: "",
            splashColor: "",
            shape: "",
            text: "",
            padding: "",
            textColor: "",
            highlightedBorderColor: "",
            disabledBorderColor: "",
            disabledTextColor: "",
            focusColor: "",
            highlightElevation: "",
            borderSide: "",
            // textTheme: "",
            onPressed: "",
          },
        },
      ],
    },
  },
  {
    text: "ListView",
    value: "ListView",
    details: {
      top: "",
      left: "",
      height: "",
      width: "",
      padding: "",
      itemExtent: "",
      scrollDirection: "",
      primary: "",
      child: [],
    },
  },
  {
    text: "CheckBoxListTile",
    value: "CheckBoxListTile",
    details: {
      top: "",
      left: "",
      height: "",
      width: "",
      title: "",
      selected: "",
      dense: "",
      checkColor: "",
      subtitle: "",
      activeColor: "",
      child: [],
    },
  },
  {
    text: "SnackBar",
    value: "SnackBar",
    details: {
      top: "",
      left: "",
      height: "",
      width: "",
      content: "",
      duration: "",
      backgroundColor: "",
      elevation: "",
      shape: "",
      child: [
        {
          text: "SnackBarAction",
          value: "SnackBarAction",
          details: {
            label: "",
            textColor: "",
            disabledTextColor: "",
            onPressed: "",
          },
        },
      ],
    },
  },
  {
    text: "AppBar",
    value: "AppBar",
    details: {
      title: "",
      backgroundColor: "",
      leading: "",
      elevation: "",
      titleSpacing: "",
      centerTitle: "",
      shadowColor: "",
      primary: "",
      shape: "",
      brightness: "",
      //textTheme: "",
      bottomOpacity: "",
      toolbarHeight: "",
      toolbarOpacity: "",
      child: [
        {
          text: "Icon",
          value: "Icon",
          details: {
            icon: "",
            color: "",
            size: "",
          },
        },
        {
          text: "Flatbutton",
          value: "Flatbutton",
          details: {
            color: "",
            splashColor: "",
            textColor: "",
            text: "",
            disabledTextColor: "",
            disabledColor: "",
            shape: "",
            //textTheme: "",
            onPressed: "",
            padding: "",
            highlightColor: "",
          },
        },
        {
          text: "CheckBox",
          value: "CheckBox",
          details: {
            activeColor: "",
            checkColor: "",
            parameter: "",
          },
        },
        {
          text: "Switch",
          value: "Switch",
          details: {
            activeColor: "",
            focusColor: "",
            activeTrackColor: "",
            hoverColor: "",
            parameter: "",
          },
        },
        {
          text: "Text",
          value: "Text",
          details: {
            textValue: "",
            style: "",
            textAlign: "",
            textDirection: "",
            maxLines: "",
            textScaleFactor: "",
          },
        },
        {
          text: "IconButton",
          value: "IconButton",
          details: {
            icon: "",
            iconSize: "",
            color: "",
            splashColor: "",
            tooltip: "",
            highlightColor: "",
            disabledColor: "",
            focusColor: "",
            padding: "",
            visualDensity: "",
            onPressed: "",
          },
        },
        {
          text: "RaisedButton",
          value: "RaisedButton",
          details: {
            color: "",
            splashColor: "",
            shape: "",
            text: "",
            padding: "",
            textColor: "",
            highlightColor: "",
            disabledColor: "",
            disabledTextColor: "",
            focusColor: "",
            elevation: "",
            //textTheme: "",
            onPressed: "",
          },
        },
        {
          text: "OutlineButton",
          value: "OutlineButton",
          details: {
            color: "",
            splashColor: "",
            shape: "",
            text: "",
            padding: "",
            textColor: "",
            highlightedBorderColor: "",
            disabledBorderColor: "",
            disabledTextColor: "",
            focusColor: "",
            highlightElevation: "",
            borderSide: "",
            // textTheme: "",
            onPressed: "",
          },
        },
        {
          text: "DatePicker",
          value: "DatePicker",
          details: {
            errorFormatText: "",
            errorInvalidText: "",
            firstDate: "",
            lastDate: "",
          },
        },
        {
          text: "TimePicker",
          value: "TimePicker",
          details: {
            helpText: "",
            cancelText: "",
            confirmText: "",
          },
        },
        {
          text: "Slider",
          value: "Slider",
          details: {
            activeColor: "",
            inactiveColor: "",
            min: "",
            max: "",
            divisions: "",
            label: "",
            parameterName: "",
            parameterValue: "",
          },
        },

        {
          text: "LinearProgressIndicator",
          value: "LinearProgressIndicator",
          details: {
            backgroundColor: "",
            valueColor: "",

            minHeight: "",
          },
        },
        {
          text: "CircularProgressIndicator",
          value: "CircularProgressIndicator",
          details: {
            backgroundColor: "",
            strokeWidth: "",
          },
        },

        {
          text: "FloatingActionButton",
          value: "FloatingActionButton",
          details: {
            //color: "",
            floatingIcon: "",
            splashColor: "",
            shape: "",
            highlightElevation: "",
            //padding: "",
            foregroundColor: "",
            backgroundColor: "",
            //disabledColor: "",
            focusColor: "",
            elevation: "",
            mini: "",
            onPressed: "",
          },
        },
        {
          text: "ToolTip",
          value: "ToolTip",
          details: {
            message: "",
            margin: "",
            padding: "",
            showDuration: "",
            toolHeight: "",
            waitDuration: "",
            iconButton: "",
            onPressed: "",
          },
        },
        {
          text: "RangeSlider",
          value: "RangeSlider",
          details: {
            activeColor: "",
            inactiveColor: "",
            min: "",
            max: "",
            divisions: "",
            startParameter: "",
            startValue: "",
            endParameter: "",
            endValue: "",
          },
        },
        {
          text: "VerticalDivider",
          value: "VerticalDivider",
          details: {
            color: "",
            thickness: "",
            endIndent: "",
          },
        },
      ],
    },
  },
  {
    text: "TabBar",
    value: "TabBar",
    details: {
      unselectedLabelColor: "",
      unselectedLabelStyle: "",
      labelStyle: "",
      labelColor: "",
      labelPadding: "",
      indicatorPadding: "",
      indicatorSize: "",
      indicatorWeight: "",
      indicatorColor: "",
      child: [
        {
          text: "Tab",
          value: "Tab",
          details: {
            icon: "",
            text: "",
            iconMargin: "",
          },
        },
      ],
    },
  },
  {
    text: "RichText",
    value: "RichText",
    details: {
      top: "",
      left: "",
      height: "",
      width: "",
      textAlign: "",
      textScaleFactor: "",
      overflow: "",
      textHeightBehavior: "",
      textWidthBasis: "",
      textDirection: "",

      child: [
        {
          text: "TextSpan",
          value: "TextSpan",
          details: {
            textName: "",
            style: "",
            recognizer: "",
          },
        },
      ],
    },
  },
  {
    text: "Container",
    value: "Container",
    details: {
      top: "",
      left: "",
      height: "",
      width: "",
      clipBehavior: "",
      color: "",
      padding: "",
      Alignment: "",
      margin: "",
      transform: "",
      foregroundDecoration: "",
      constraints: "",
      decoration: "",
      child: [],
    },
  },
  {
    text: "Row",
    value: "Row",
    details: {
      top: "",
      left: "",
      height: "",
      width: "",
      mainAxisAlignment: "",
      mainAxisSize: "",
      crossAxisAlignment: "",
      verticalDirection: "",
      textDirection: "",
      textBaseline: "",
      child: [],
    },
  },
  {
    text: "Column",
    value: "Column",
    details: {
      top: "",
      left: "",
      height: "",
      width: "",
      mainAxisAlignment: "",
      mainAxisSize: "",
      crossAxisAlignment: "",
      verticalDirection: "",
      textDirection: "",
      textBaseline: "",
      child: [],
    },
  },
  {
    text: "Image",
    value: "Image",
    details: {
      top: "",
      left: "",
      height: "",
      width: "",
      url: "",
      imageHeight: "",
      imageWidth: "",
      fit: "",
      color: "",
      cacheHeight: "",
      cacheWidth: "",
      centerSlice: "",
      Alignment: "",
      repeat: "",
      colorBlendMode: "",
      gaplessPlayback: "",
      isAntiAlias: "",
      matchTextDirection: "",
      onTap: "",
    },
  },
  {
    text: "TextStyle",
    value: "TextStyle",
    details: {
      fontSize: "",
      fontWeight: "",
      backgroundColor: "",
      color: "",
      height: "",
      letterSpacing: "",
      textBaseline: "",
      wordSpacing: "",
      inherit: "",
      shadowColor: "",
      shadowOffset: "",
      shadowBlurRadius: "",
    },
  },
  {
    text: "InputDecoration",
    value: "InputDecoration",
    details: {
      labelText: "",
      filled: "",
      enabled: "",
      icon: "",
      fillColor: "",
      hintText: "",
      disabledBorderColor: "",
      disabledBorderStyle: "",
      disabledBorderWidth: "",
      disabledBorderRadius: "",
      disabledGapPadding: "",
      focusColor: "",
      focusedBorderColor: "",
      focusedBorderStyle: "",
      focusedBorderWidth: "",
      focusedBorderRadius: "",
      focusedGapPadding: "",
      prefixIcon: "",
      suffixIcon: "",
      enabledBorderColor: "",
      enabledBorderStyle: "",
      enabledBorderWidth: "",
      enabledBorderRadius: "",
      enabledGapPadding: "",
    },
  },
  {
    text: "BoxDecoration",
    value: "BoxDecoration",
    details: {
      topRightRadius: "",
      topLeftRadius: "",
      bottomRightRadius: "",
      bottomLeftRadius: "",
      color: "",
      backgroundBlendMode: "",
      boxShadowColor: "",
      boxShadowOffset: "",
      boxShadowBlurRadius: "",
      boxShadowSpreadRadius: "",
    },
  },
  {
    text: "RoundedRectangleBorder",
    value: "RoundedRectangleBorder",
    details: {
      borderSideColor: "",
      borderSideWidth: "",
      borderSideStyle: "",
      borderRadius: "",
    },
  },
  {
    text: "BottomNavigationBar",
    value: "BottomNavigationBar",
    details: {
      type: "",
      selectedItemColor: "",
      unselectedItemColor: "",
      iconSize: "",
      elevation: "",
      selectedFontSize: "",
      showSelectedLabels: "",
      pageNames: "",
      child: [
        {
          text: "BottomNavigationBarItem",
          value: "BottomNavigationBarItem",
          details: {
            Icon: "",
            title: "",
            backgroundColor: "",
          },
        },
      ],
    },
  },
  {
    text: "DropdownButton",
    value: "DropdownButton",
    details: {
      top: "",
      left: "",
      height: "",
      width: "",
      Icon: "",
      iconSize: "",
      iconDisabledColor: "",
      iconEnabledColor: "",
      elevation: "",
      dropdownColor: "",
      isDense: "",
      isExpanded: "",
      focusColor: "",
      autofocus: "",
      parameterName: "",
      paramValue: "",
      child: [
        {
          text: "DropdownMenuItem",
          value: "DropdownMenuItem",
          details: {
            text: "",
            value: "",
          },
        },
      ],
    },
  },
  {
    text: "PopupMenuButton",
    value: "PopupMenuButton",
    details: {
      top: "",
      left: "",
      height: "",
      width: "",
      Icon: "",
      shape: "",
      elevation: "",
      color: "",
      captureInheritedThemes: "",
      enabled: "",
      tooltip: "",
      padding: "",
      offset: "",
      initialValue: "",
      child: [
        {
          text: "PopupMenuItem",
          value: "PopupMenuItem",
          details: {
            text: "",
            value: "",
            textStyle: "",
            enabled: "",
            height: "",
          },
        },
        {
          text: "CheckedPopupMenuItem",
          value: "CheckedPopupMenuItem",
          details: {
            text: "",
            value: "",
            checked: "",
            enabled: "",
          },
        },
      ],
    },
  },
];
